<?php


namespace App\Form;


use App\Data\SearchCateg;
use Doctrine\DBAL\Types\TextType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CategoryType extends AbstractType
{

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('q', TextType::class, [
                'label'=> false,
                'required'=>false,
                'attr' =>[
                    'placeholder' => 'Search'
                ]
            ] );

    }

    public function configureOptions(OptionsResolver $resolver)
{

    $resolver->setDefaults([
       'data_class'=> SearchCateg::class,
        'method'=>'GET',
        'csrf_protection'=>false
    ]);



}

public function getBlockPrefix()
{
    return parent::getBlockPrefix(); // TODO: Change the autogenerated stub
    return '';
}
}