# Read the documentation: https://symfony.com/doc/current/bundles/StofDoctrineExtensionsBundle/index.html
# See the official DoctrineExtensions documentation for more details: https://github.com/Atlantic18/DoctrineExtensions/tree/master/doc/

stof_doctrine_extensions:
  default_locale: en_US
  uploadable:
    default_file_path: "%kernel.project_dir%/../public"
    mime_type_guesser_class: Stof\DoctrineExtensionsBundle\Uploadable\MimeTypeGuesserAdapter
    default_file_info_class: Stof\DoctrineExtensionsBundle\Uploadable\UploadedFileInfo
  orm:
    default:
      uploadable: true