vich_uploader:
  db_driver: orm
  mappings:
    users_images:
      uri_prefix: /images/users
      upload_destination: '%kernel.project_dir%/public/images/users'

  #mappings:
  #    products:
  #        uri_prefix: /images/products
  #        upload_destination: '%kernel.project_dir%/public/images/products'
